# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-18 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grupoalumnos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupoalumnos',
            unique_together=set([('Usuario', 'Grupo')]),
        ),
    ]
