# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_juego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
