# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-22 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20171119_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.TimeField()),
                ('intentos', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Juego')),
            ],
        ),
    ]
