# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_resultados_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultados',
            name='intentos',
        ),
        migrations.AddField(
            model_name='resultados',
            name='instrucciones',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultados',
            name='tiempo',
            field=models.CharField(max_length=12),
        ),
    ]
